# Constructor


##배열 생성 함수
*   np.zeros((x, y)) -> x행 y열, 원소는 0
*   np.ones((x, y)) -> x행 y열, 원소는 1
*   np.eye(x) -> x행 x열, 단위 행렬
* np.arange([start], end, [step]) == np.array(range([start], end, [step]))
* np.linspace(start, end, num = x) -> 크기가 num인 실수 배열, 원소들이 start~end까지 균등한 간격을 가짐
* np.logspace(start, end, num = x) -> 크기가 num인 실수 배열, 10<sup>start</sup> ~ 10<sup>end</sup>까지 로그 스케일로 균등한 간격 num개



In [88]:
import numpy as np
print(np.zeros((3, 4)))
print(np.ones((3, 4)))
print(np.eye((3)))
print(np.arange(10, -10, -1))
print(np.linspace(1, 10, num=10))
print(np.logspace(0, 3, num=4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[   1.   10.  100. 1000.]


##넘파일 배열 수정 메서드
* npArray.reshape(shape)
* npArray.flatten()

In [ ]:
arr = np.arange(8)
print(arr)
print()

arr2 = arr.reshape(2, 4)
print(arr2)
print()

print(arr2.flatten() == arr2.reshape(-1))
print(arr2.flatten(), arr2.reshape(-1))
print(arr2.reshape(4, -1))
print(arr2.reshape(-1, 8)) # 행은 알아서, 열은 8
print(arr2.reshape(8, -1)) # 행은 8행 열은 알아서

[0 1 2 3 4 5 6 7]

[[0 1 2 3]
 [4 5 6 7]]

[ True  True  True  True  True  True  True  True]
[0 1 2 3 4 5 6 7] [0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


#Random



##난수 배열 생성
* np.random.seed(n) -> 난수 생성 초기값
* np.random.rand(10) -> 크기가 10인 1차원 배열, 원소는 0과 1사이
* np.random.randint(start, end, size = shape) -> shape 모양의 난수 배열, 원소는 start ~ end - 1 사이

In [ ]:
np.random.seed(1)

rnd = np.random.rand(10)
print(rnd * 10 + 20) # 20과 30사이의 난수

rnd2 = np.random.randint(1, 11, size = (10, 10))
print(rnd2) # 1과 10사이

print(np.random.randint(1, 6, size = 9))

[24.17022005 27.20324493 20.00114375 23.02332573 21.46755891 20.92338595
 21.86260211 23.45560727 23.96767474 25.38816734]
[[ 6  3  5  3  5  8  8 10  2  8]
 [ 1  7 10 10  8  7 10  2  1  2]
 [ 9  9  4 10  9  8  4  7  6  2]
 [10  4  5  9  2  5  1  4 10  3]
 [ 1  5 10  3  8  8 10  9  7 10]
 [ 4  8  8  5  6 10  4  7  9  1]
 [ 3  8  8 10  8  4  1  9  8  8]
 [ 2  2  4  1  9  7  5  6  7  3]
 [ 6  8  9  5  5  8  8  5 10  1]
 [ 3  1  8  2  8 10  9  5  1  2]]
[5 2 1 3 4 2 3 5 5]


##정규 분포 난수 (균일한 확률 분포의 난수 생성)
* np.random.normal(mean, standart_deviation, shape)
* np.random.randn(shape) == np.random.normal(0, 1, shape)

In [ ]:
np.random.seed(1)
norm = np.random.normal(0, 1, 5)

np.random.seed(1)
rndn = np.random.randn(5)
print(norm) # 길이가 5인 1차원 배열, 원소는 평균이 0, 표준 편차가 1
print(rndn) # 위 결과와 동일
print(norm == rndn)
print()

np.random.seed(1)
norm2 = np.random.normal(10, 2, (5, 5))
np.random.seed(1)
rndn2 = np.random.randn(5, 5)
print(norm2)
print(rndn2 * 2 + 10)
print(norm2 == rndn2 * 2 + 10)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
[ True  True  True  True  True]

[[13.24869073  8.77648717  8.9436565   7.85406276 11.73081526]
 [ 5.39692261 13.48962353  8.4775862  10.63807819  9.50125925]
 [12.92421587  5.87971858  9.35516559  9.23189129 12.26753888]
 [ 7.80021747  9.65514358  8.24428316 10.08442749 11.16563043]
 [ 7.79876165 12.28944742 11.80318144 11.00498868 11.8017119 ]]
[[13.24869073  8.77648717  8.9436565   7.85406276 11.73081526]
 [ 5.39692261 13.48962353  8.4775862  10.63807819  9.50125925]
 [12.92421587  5.87971858  9.35516559  9.23189129 12.26753888]
 [ 7.80021747  9.65514358  8.24428316 10.08442749 11.16563043]
 [ 7.79876165 12.28944742 11.80318144 11.00498868 11.8017119 ]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


##난수 관련 함수
* np.random.shuffle(array) -> 넘파이 배열 순서 랜덤 변경 (원본 변경)
* np.random.permutation(array) -> 넘파이 배열 순서 변경한 배열을 반환(원본 유지)
* np.random.choice(array, n) -> arr에서 n개의 원소를 균등 확률로 추출한 배열 반환
 * replace = False -> 중복 추출 제외
 * replace = True -> 중복 추출 가능
 * p = [] -> array의 원소들마다 추출 확률 값을 가지는 리스트

In [84]:
x = np.arange(10) + 1
np.random.shuffle(x)
print(x)

y = np.arange(10) + 1
print(np.random.permutation(y))
print(y) # 원본 유지

fruits = ['apple', 'banana', 'grapes', 'cherries', 'durian', 'lemon', 'mango']
pd = [0.1, 0, 0.2, 0.5, 0.1, 0.05, 0.05]
print(np.random.choice(fruits, 3, replace = False, p = pd))

[ 6  2  5 10  4  7  3  9  8  1]
[ 5  7  9  2  1 10  4  6  3  8]
[ 1  2  3  4  5  6  7  8  9 10]
['lemon' 'durian' 'cherries']


# Method


##전치 행렬 변환 (n, m) -> (m, m)
* arr.T == arr.transpose()

In [99]:
arr = np.arange(1,7).reshape(2, 3)
print(arr)
print(arr.T)
print(arr.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


##평균 계산
* np.mean(arr, axis=0)
* arr.mean(axis = 0)
 * axis = 0 -> 행 방향, 결과는 각 열마다 평균값
 * axis = 1 -> 열 방향, 결과는 각 행마다 평균값

In [100]:
arr = np.array([
    [99, 93, 60],
    [68, 73, 32],
    [50, 61, 81],
    [69, 26, 79],
])
print(arr)
print()

print(np.mean(arr, axis = 0)) # 각 열의 평균
print(arr.mean(axis = 0))

print(np.mean(arr, axis = 1)) # 각 행의 평균
print(arr.mean(axis = 1))

[[99 93 60]
 [68 73 32]
 [50 61 81]
 [69 26 79]]

[71.5  63.25 63.  ]
[71.5  63.25 63.  ]
[84.         57.66666667 64.         58.        ]
[84.         57.66666667 64.         58.        ]


## unique() 함수
넘파이 배열의 고유 값 출력

In [101]:
a = np.array([
    [2, 3, 2],
    [2, 3, 2],
    [3, 2, 3],
])
print(np.unique(a)) # 모든 원소들 중 고유 값
print(np.unique(a, axis=0)) # 고유한 값을 가진 행 출력
print(np.unique(a, axis=1)) # 고유한 값을 가진 열 출력

[2 3]
[[2 3 2]
 [3 2 3]]
[[2 3]
 [2 3]
 [3 2]]


## 배열 합치기 concatenate
np.concatenate((arr1, arr2), axis)
* 두 배열이 1차원일 때 -> 열 방향으로 연결
* 두 배열이 2차원일 때 -> axis = 0이면 행이 늘어남, 1이면 열이 늘어남

In [104]:
arr1 = np.arange(8).reshape(2, 4)
arr2 = np.arange(8, 16).reshape(2, 4)
print(arr1)
print(arr2)
print()

print(np.concatenate((arr1, arr2), axis = 0)) # 행이 늘어남
print(np.concatenate((arr1, arr2), axis = 1)) # 열이 늘어남

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


## 배열 분리 split()
np.split(arr, n, axit)
* 두 배열이 1차원일 때 -> 열 방향 n개의 배열로 분리 == np.hsplit(arr, n)
* 두 배열이 2차원일 때
 * axis = 0 -> 행 방향 n개의 배열로 분리 == np.vsplit(arr, n)
 * axit = 1 -> 열 방향 n개의 배열로 분리 == np.hsplit(arr, n)

In [115]:
arr1 = np.arange(8).reshape(2, 4)
print(arr1)
print()

up, down = np.split(arr1, 2, axis = 0) # 행방향으로 분리
up2, down2 = np.vsplit(arr1, 2)
print(up)
print(down)
print(up == up2)
print(down == down2)
print()

left, right = np.split(arr1, 2, axis=1)
left2, right2 = np.hsplit(arr1, 2)
print(left)
print(right)
print(left == left2)
print(right == right2)

[[0 1 2 3]
 [4 5 6 7]]

[[0 1 2 3]]
[[4 5 6 7]]
[[ True  True  True  True]]
[[ True  True  True  True]]

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


## 기타 넘파이 함수
* np.all(arr) -> 모든 원소가 참이면 True
* np.any(arr) -> 원소 하나라도 참이면 True
* np.isnan(arr) -> 원소가 NaN값이면 True, 논리배열 반환
* np.isfinite(arr) -> 원소가 np.NaN 또는 np.inf라면 False, 논리배열 반환

In [132]:
arr1 = np.array([1,0,1,0])
print(np.all(arr1))
print(np.any(arr1))
print()
arr2 = np.array([1, np.NaN, 1, 0, float("inf"), np.inf])
print(arr2[-1] == arr2[-2])
print(np.isnan(arr2))
print(np.isfinite(arr2))

print(arr2[np.isfinite(arr2)])

False
True

True
[False  True False False False False]
[ True False  True  True False False]
[1. 1. 0.]
